### ISSUE TITLE
Generate random string values to not encounter  duplicate entry issues

### ISSUE THREAD

**Issue by armorKing11** [rwnx/pynonymizer#106]
**Is your feature request related to a problem? Please describe.**
Currently when you try to  anonymize a  column say (**sys_id**) of type VARCHAR and if it has duplicate foreign keys , pynonymizer throws error 
```
Duplicate entry '0efg4t5fs5d-test1' for key 'api_product_id_sys_id'
```
where  for **api_product_id = 0yb6h5jfs5d**  , **api_product_id** the foreign key
and for **sys_id = test1**, `sys_id` is the column to be updated

when using a strategy file as below
```
tables:
  system:
    columns:
      sys_id: ( 'test1' )
```

How can i specify in the strategy file to generate random string values  without using the  faker lbrary generators ?
The faker library does not guarantee  unique values cos when i tried with say `word` faker generator , it still gave me an error and failed
```
ERROR 1050 (42S01) at line 1: Table '_pynonymizer_seed_fake_data' already exists
```
And for a large number of rows ,the faker library generators adds an overhead  (since it needs to generate the value and insert it )slowing down the anonymization process .
I know that there is a RAND() function , but that generates a value from 0 to 1 . Can that be used to say generate a value range lke
```
test1
test2
test3
```
or 
```
sdfsd
evbrr
dfdgd
```

And why does pynonymizer check the combination of foreign key and the column to be updated instead of the primary key and the column to be updated ?

**Describe the solution you'd like**

Have either a way to combine a string value and the RAND() function possibly ,like `(  'test' + RAND() )` or a random string generator where you could specify the length of the string like `( RAND_STR(5) )` where 5 is the length of the string 

**Describe alternatives you've considered**

**Additional context**

**Comment by rwnx** [comment]
Hi, here are some things i might be able to answer for you:

pynonymizer is only really a fancy harness for running sql statements. that error is coming from the database - pynonymizer does no 'check'

[the `fake_update` strategy _does not provide unique values_. ](https://github.com/rwnx/pynonymizer/blob/master/doc/strategyfiles.md#column-strategy-fake_update)

There is some more discussion on 'uniqueness' in this issue: https://github.com/rwnx/pynonymizer/issues/86

For uniqueness, you have two options: 
1. use a unique_login column strategy (a random string)
https://github.com/rwnx/pynonymizer/blob/master/doc/strategyfiles.md#column-strategy-unique_login

2. design your own random string using the appropriate literal for your db. e.g. in your example: `(select CONCAT('test', RAND()) )`
https://github.com/rwnx/pynonymizer/blob/master/doc/strategyfiles.md#column-strategy-literal
https://stackoverflow.com/questions/16737910/generating-a-random-unique-8-character-string-using-mysql

**Comment by armorKing11** [comment]
Thank you very much for your guidance @rwnx , appreciate  it !!

**Comment by rwnx** [comment]
I'm closing this issue now as it seems that we've resolved the uncertainty here.
