### ISSUE TITLE
Improve deployability: Dockerize pynonymizer

### ISSUE THREAD

**Issue by LDan1117** [rwnx/pynonymizer#136]
**Is your feature request related to a problem? Please describe.**
Yes. Installing all dependencies that are needed for `pynonymizer` to run requires quite a lot of effort which could be saved by publishing Docker images with everything baked in.

**Describe the solution you'd like**
In a nutshell, public images on Docker Hub with support for PostgreSQL, MySQL, and SQL Server would be nice.

**Additional context**
While assessing this tools I created a simple Dockerfile that represents the idea. https://github.com/LDan1117/pynonymizer.docker/blob/main/Dockerfile
However, it's not production ready as lots of things should still be tailored. E. g. freezing dependencies, mounting volumes with strategy files, restricting application access, etc.

**Comment by rwnx** [comment]
Hey! this sounds like a great idea. I'd love it if you could create a PR to get a first draft of this into the repo, then I could pick it up and look at getting pynonymizer "official" images published on docker hub? 

I know you said it's not production ready, but we could totally build on what you've got!

**Comment by rwnx** [comment]
Hi, 
As a beta, I've added some official images with the mssql client here: https://hub.docker.com/r/rwnxt/pynonymizer/tags

Can you take a look and come back to this thread if this isn't what you're looking for?

Thanks

Rowan
