### ISSUE TITLE
Error with parameter --skip-steps

### ISSUE THREAD

**Issue by seb49** [rwnx/pynonymizer#152]
Hi,

It's a great job you have done.

I discover a mistake with the parameter --skip-steps, the code it wait --skip_steps whith underscore

https://github.com/rwnx/pynonymizer/blob/cead26199bfda1b4e4c179d5f314f5ec682f8c11/pynonymizer/cli.py#L67

Regards

**Comment by rwnx** [comment]
Great spot! that will be fixed over the next few days. Thanks for the report!

**Comment by rwnx** [comment]
should be fixed in v2.1.1, please comment if you continue to have issues!
