### ISSUE TITLE
PYNONYMIZER_STRATEGY dropped without deprecation

### ISSUE THREAD

**Issue by simonblake-mp** [rwnx/pynonymizer#159]
**Describe the bug**
A working v1.x pynonymizer config that has env var `PYNONYMIZER_STRATEGY` set is failing with v2  :

```
Missing values for required arguments:
Missing INPUT
Missing STRATEGYFILE
```

There's no mention in the CHANGELOG of `PYNONYMIZER_STRATEGY` being deprecated vs `PYNONYMIZER_STRATEGYFILE` - I'm wondering if it's been unintentionally dropped, as at the moment it's a breaking change without a prior deprecation?

**To Reproduce**
as above

**Expected behavior**
either `PYNONYMIZER_STRATEGY` continues to work, or a deprecation message

**Additional context**

**Comment by simonblake-mp** [comment]
likewise, `PYNONYMIZER_START_AT` (and presumably `PYNONYMIZER_STOP_AT`) have also been dropped without doc changes or a deprecation warning?

**Comment by rwnx** [comment]
Hi, thanks for reporting this. It looks like this was accidentally changed because of the differences in argument names in the new CLI library I'm using. This is absolutely a bug and I will restore the previous behaviour. I've added this to v2.2.1, stay tuned for updates.

**Comment by rwnx** [comment]
PYNONYMIZER_START_AT has been accidentally renamed to PYNONYMIZER_START_AT_STEP. I'll make sure this behaviour is reverted.

**Comment by simonblake-mp** [comment]
I've changed my pipelines to use the new variable names, other folks have probably done the same - might be nice to deprecate the new names rather than just a revert?

**Comment by rwnx** [comment]
Good suggestion, thanks! Both variations will be supported in 2.2.1. Closing this, but let's keep talking if it's not fixed.
