### ISSUE TITLE
Connectionstring fix

### ISSUE THREAD

**Issue by manmetbaardt** [rwnx/pynonymizer#167]
Last week I installed the lastest version, with the verbose setting fixed, and after a few tests, I found out why the connectionstring was not working.
In the file pynonymizer_env\Lib\site-packages\pynonymizer\database\mssql\__init__.py around line 77, the variable db_host is hardcoded as local.
![image](https://github.com/rwnx/pynonymizer/assets/169888533/ae4a4a9a-b2e9-4200-8d20-9d522584c718)
After commenting this line, the package worked with command below
pynonymizer --strategy "C:\Temp\strategy_MISC.json" --db-type mssql --only-step ANONYMIZE_DB  --db-host '[xxxxxserverxxxx.xxx.xxx.xx](http://xxxxxserverxxxx.xxx.xxx.xx/)' --db-name 'xxx_xxx_Anonymous' --db-user 'pynon' --db-password 'pynon' --verbose
Would it possible to remove the line from the package ?

**Comment by rwnx** [comment]
It's there because the dump db options dont work when the server is remote. I think this could be replaced with a warning, rather than an override. I will schedule this for the next version.

**Comment by rwnx** [comment]
Released a fix for this in v2.4.0 today!
