### ISSUE TITLE
Improve Programmatic Invocation: Callbacks/events/hooks

### ISSUE THREAD

**Issue by rwnx** [rwnx/pynonymizer#33]
**Is your feature request related to a problem? Please describe.**
pynonymizer is a long, blocking process. If you're going to invoke it from another function, it would be nice to know what the hell is happening as it executes. 

**Describe the solution you'd like**
key places, likely conditional on steps, that you are able to recieve signals to run your own code, and clearly defined failure behaviour.

**Comment by jerometwell** [comment]
An Update on this one. to tie in with #31  I think that things like the progressbar updates should be uplifted to `cli.py`, and this would be a good solution to this issue. I'm not 100% sure on what the de facto event/signalling mechanism in python is, so i'd appreciate any suggestions! 

My initial thoughts were just to allow functions to be added to callbacks in-the-style-of observers.

**Comment by rwnx** [comment]
Closing as stale and out of scope. Please open a discussion if you wanted this feature!  https://github.com/rwnx/pynonymizer/discussions
