### ISSUE TITLE
help with dob

### ISSUE THREAD

**Issue by amz4u2nv** [rwnx/pynonymizer#90]
Hi, im trying to create a db strategy yml file, where the dob generated should be between certains dates, cause they need to be 18 or above of age.
Any help, would be much appreciated.

**Comment by stoiven** [comment]
You prolly can do something with a type literal and then use some `sql` to generate it @amz4u2nv

**Comment by amz4u2nv** [comment]
Thanks,
Is there any example, of using this 
date_between_dates

**Comment by stoiven** [comment]
If you're doing >18 age, can you filter via based on the table? Like for example
```
mysql> select * from person;
+-----+----------+--------+------+
| number | name  | gender | age  |
+-----+----------+--------+------+
| 114    | kev    | m    |  18   |  
| 115    | brian  | m    |  18   | 
+-----+----------+--------+------+
```
`select * from table_name
where  timestampdiff(year,age,curdate()) > 50`

Or something like this

**Comment by amz4u2nv** [comment]
My bad at not explaining it, I’m trying to generate a fake dob but need the dob to be set so that they are all over 18

**Comment by rwnx** [comment]
you should be able to use the [date_between](https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html#faker.providers.date_time.Provider.date_between) provider in the way you mentioned, using the fake_args feature. 

```yaml
column_name: 
  type: fake_update
  fake_type: date_between
  fake_args:
    start_date: "-50y"
    end_date: "-18y"
```

You can read more about how passing args to generators works in the [docs](https://github.com/rwnx/pynonymizer/blob/master/doc/strategyfiles.md#column-strategy-fake_update). 

Let me know how you get on ✨

**Comment by amz4u2nv** [comment]
Thanks @rwnx, that did the trick
I was trying to use date_between_dates - 
like below

      date_of_birth:
        type: fake_update
        fake_type: date_between_dates
        fake_args:
          start_date: '1975-01-01'
          end_date: '2001-01-01'

but got this error - 
Unsupported Fake type: date_between_dates: dict_keys(['start_date', 'end_date'])
Not sure why this didnt work, do you know where the best place to see if my keys are correct and if the date inputs are in the correct format.

Thanks

**Comment by amz4u2nv** [comment]
the version of pynonymizer is 1.21.3
faker 11.3.0
I didn't choose explicity a locale but tried it with and without
pynonymizer -u root -p root -i test1.sql -s table_strategy.yml -o testdumpanon.sql

tables:
  applicant_applicant:
    columns:
      firstName: first_name
      lastName: last_name
      dateOfBirth:
        type: fake_update
        fake_type: date_between_dates
        fake_args:
          start_date: '1975-01-01'
          end_date: '2003-01-01'

Also taking out the fake_args in the above example, doesn't show any error, but it requires the params to make it work correctly.

**Comment by amz4u2nv** [comment]
yup that did the trick...my bad, should have spotted that.
date_between work absolutely fine, it was just when i trying to figure out how to resolve it, I came across date_between_dates, and was just wandering why it didn't work for me.

Thanks for all your help, much appreciated.
